### ISSUE TITLE
Pump does not handle end of stream

### ISSUE THREAD

**Issue by Xophe** [eclipse-vertx/vert.x#1465]
Here's the code of the Pump :

``` java
PumpImpl(ReadStream<T> rs, WriteStream<T> ws) {
    this.readStream = rs;
    this.writeStream = ws;
    drainHandler = v-> readStream.resume();
    dataHandler = data -> {
      writeStream.write(data);
      incPumped();
      if (writeStream.writeQueueFull()) {
        readStream.pause();
        writeStream.drainHandler(drainHandler);
      }
    };
  }
```

I think this method should have the following last line in order to handle the end of the reading stream :

``` java
rs.endHandler(v -> ws.end());
```

**Comment by vietj** [comment]
yes before it was not possible because end() did not exist in WriteStream.

however I would rather add that later with a study to see how it behaves, for example AsyncFile#end() will close the file, so if a user has already some code doing that the file would be closed twice. Which is not a problem for AsyncFile per se, but you seem y point, it will change the behavior of existing pump constructs.

**Comment by vietj** [comment]
this is not possible with the new Pipe API in Vert.x 3.7.0
