### ISSUE TITLE
No way to disable file caching in 3.3.2

### ISSUE THREAD

**Issue by nickhod** [eclipse-vertx/vert.x#1528]
There appears to be no way to disable file caching.

```
System.setProperty("vertx.disableFileCaching", "true");
```

has no effect. Using the vertx launcher with the following arguments

```
run {verticle} -conf {conf} -Dvertx.disableFileCaching=true
```

also has no effect. I'm having to restart the server each change.
I note issue #1514 and the fix but it seems like command switch should work even with a static initializer.

**Comment by nickhod** [comment]
'''
-Dvertx.disableFileCPResolving=true
'''

Does work as a last resort. Relative paths change however.

**Comment by testn** [comment]
Ideally, it should be exposed as "VertxOption"

**Comment by vietj** [comment]
@pmlopes @cescoffier your take on this ? 

in relationship with https://github.com/eclipse/vert.x/pull/1515

**Comment by cescoffier** [comment]
@vietj @pmlopes I'm having a look.

**Comment by cescoffier** [comment]
What do you mean by file caching ? Do you mean extracting the file on the file system ? There is no option for now to avoid files embedded in a fat jar to be served without being copied on the file system first. 

Disable file caching means that once copied to the file system, it won't retry to read it from the source jar file.

Files are stored in the `.vertx` directory.

**Comment by nickhod** [comment]
My aim was for files to be read from the OS filesystem each time. To someone who's not familiar with Vertx internals "disableFileCaching" sounded like the right option.

The are three terms at play here: classpath / embedded files, the Vertx filesystem (.vertx) and the OS filesystem. The documentation doesn't make the distinction totally clear (to someone new to Vertx) how disableFileCaching and disableFileCPResolving relate to each.

It seems like "disableCPFileCaching" would be a more relevant name if it has no effect on files read directly from the OS filesystem.

**Comment by cescoffier** [comment]
I understand now. Yes the "wording" is not perfect.

When Vert.x needs to read a file from a jar, a zip or an url, it unpacks it on the file system first (in the `.vertx` dir). This is because reading from a jar or a zip is blocking (input stream), while we can read from the FS in a non-blocking way. 

When the file caching is enabled, the file is unpacked once and read from there.  When you disable the cache, the file is always read from its original location, copied to the `.vertx` dir and read from there.

`disableFileCPResolving` enables / disables whether or not Vert.x should resolve file from the its classloader in addition from the file system. Disabling it is not without consequences, as you can only server / load / read files from the file system, and not the file that are embedded in jar files (classpath, fat jar) or in the zip files...

**Comment by cescoffier** [comment]
If I understand correctly you would need an option to not write the file to the `.vertx` directory at all. Am I right ?

**Comment by nickhod** [comment]
Thanks for the clarification. `disableFileCPResolving` does what I need for this project as I don't need to load from the classpath / fatjar and we do our own in-memory caching.

I can envisage a scenario where I want to read "static" files from the classpath / fat jar (which can be cached in .vertx) and "dynamic" OS filesystem files (that can't be cached). It seems like that would be impossible with Vertx at the moment, if I understand correctly?

Maybe a `disableOSFileCaching` option would allow that to be possible?

**Comment by cescoffier** [comment]
@nickhod the cache is not use for every file. If you are using files form the file system, you should use the Vert.x FileSystem which would let you implement what you need.
