### ISSUE TITLE
When will Vertx add support for BKS keystore/truststore type ?

### ISSUE THREAD

**Issue by sophieqianCA** [eclipse-vertx/vert.x#1768]
We are using Vertx in our project, I noticed it only supports JKS/PKCS12 format for TLS mode. We are using Bouncy Castle  keystore/truststore, can Vertx add support for BKS format?  If so,  how soon will it take to get in? Thanks

**Comment by vietj** [comment]
@sophieqianCA where is this format described ? is BC library mandatory for using it

**Comment by sophieqianCA** [comment]
@vietj Thanks for the quick response. 

We are using Bouncy castle for Fips support, (you can check the doc at
https://www.bouncycastle.org/fips/UserGuide-20151229.pdf), we are using BCFKS format.

BC library will be passed in the  CLASSPATH.

Our requirement is we'd like vertx to remove the constraint on type( no JKS and PKCS12 restriction), make it take the provider type defined in java.security and  keystore type from JVM properties.

We override java.security when start JVM,  with following changes:

security.provider.1=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.2=com.sun.net.ssl.internal.ssl.Provider BCFIPS
security.provider.3=sun.security.provider.Sun

We wants vertx to accept the provider type BCFIPS and ketstore type BKFCS. 

We passed following as JVM paramaters.
-Djava.security.properties==/etc/security/java.security -Djavax.net.ssl.keyStoreProvider=BCFIPS -Djavax.net.ssl.trustStoreProvider=BCFIPS -Djavax.net.ssl.keyStore=/etc/myapp/keystore.bcfks 
-Djavax.net.ssl.keyStorePassword=pw -Djavax.net.ssl.trustStore=/etc/myapp/truststore.bcfks -Djavax.net.ssl.trustStorePassword=pw
 
Let me know if you need more info

Thanks

**Comment by vietj** [comment]
Hi, we cannot add BC library to Vert.x Core, I believe however it could be possible to integrate this library to load content by implementing KeyCertOptions / TrustOptions and override the `getKeyManagerFactory/getTrustManagerFactory` methods.

So you could come up (and contribute to the community) with an implementation of these interfaces for this store.

**Comment by sophieqianCA** [comment]
@vietj We are not asking  you to add BC library to Vertx core, we just want to pass the java.security and bcfips library to JVM, so JVM knows which security provider to use. Can Vertx add a new TYPE parameter for  keystore, so we can pass in.  When keystore.load been invoked, it will load the one we wanted , instead of using default JKS type. Thanks

**Comment by hackorama** [comment]
Will this approach work, without adding Bouncy Castle dependencies to Vert.x but allowing external configuration of key store type.

- Add key store type as a new option to JksOptions, type will be "jks" by default.
- In ``KeyStoreHelper`` in each [loadStore](https://github.com/eclipse/vert.x/blob/65a1050b0922de38329cdbe90c5ecd8094a93a04/src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java#L200) change the key store get instance to use key store specified from JksOptions



``KeyStore.getInstance("jks")`` to something like ``KeyStore.getInstance(jksOptions.getType())``

A user who has Bouncy Castle dependencies in their application class path and has BC key store provider loaded at the JDK level through ``java.security`` file changes can then set ``JksOptions.setType("BKS")`` and use the BC key store with Vert.x ?

**Comment by EXTERNALCOREWORKS** [comment]
Hi @vietj , I believe the @hackorama approach should work, is it possible to pull this up soon ? In the upcoming versions ? Thanks in advance.

**Comment by vietj** [comment]
we will make this easier I think by providing a way to subclass JKS options

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/issues/3591

**Comment by EXTERNALCOREWORKS** [comment]
Hi @vietj for some reason we are perceiving either a potential regression or a change introduced in Vertx 4.4.0 impacting the usage of the solution https://github.com/eclipse-vertx/vert.x/issues/3591 that I've been using for a while. Here its the analysis:

**Our Code:**
 
KeyStoreOptions ksOpt = new KeyStoreOptions().**setType**(type).setPath(keyStoreAbosultePath).setPassword(keyStorePassword);
HttpServerOptions httpServerOptions = new HttpServerOptions().**setKeyCertOptions**(ksOpt).setSsl(true);
 
**Vert.x 4.1 to Vert.x 4.3.8**      Our web application works without issue in FIPS and non FIPS mode.
 
FIPS mode, following params been passed in
Keystore type: **BCFKS**
Keystore provider: **BCFIPS**
 
**Vert.x 4.4.0 to 4.5.1**
After upgraded to  Vert.x 4.4.0 to 4.5.1, we get the following error in FIPS mode, none FIPs mode works with no issue.
 
![image](https://github.com/eclipse-vertx/vert.x/assets/18219609/3101f573-3f25-4960-9659-e8e1f0f085d7)

After looking at the commits on GitHub, traced down to the change related to "Create SNI KeyManagerFactory in KeyCertOptions instead of SslContextProvider so it can be cached"
 
https://github.com/eclipse-vertx/vert.x/pull/4695
 
https://github.com/eclipse-vertx/vert.x/pull/4694
 
 
_We suspect the above change caused the regression for FIPS mode._


As to our understanding, the Keystore type we passed in from KeyStoretOptions using setKeyCertOptions()  is not been  taken.

KeyStoreHelper. toKeyManagerFactory() method is calling KeyStore.getDefaultType(), which seems always return back “JKS”.

Which caused the regression to our existing  code.

Please let us know if our suspicion is true, or if there is a new way to use the solution, and guide us how.
Thanks in advance.

**Comment by EXTERNALCOREWORKS** [comment]
Hi @vietj any chance checking the reported behaviour above ? Any clues ? Thanks in advance.

**Comment by tsegismont** [comment]
Can you provide a reproducer in a separate issue?
