### ISSUE TITLE
Measuring the event-loop 

### ISSUE THREAD

**Issue by marcust** [eclipse-vertx/vert.x#2349]
So I stumbled upon
`    // No metrics, we are on the event loop.`
and was wondering what one has to do with the other? Why shouldn't I want to measure my eventloop throughput?

**Comment by vietj** [comment]
the event loop process a lot of metrics and typically measuring them would affect performance, so it's rather a deliberate choice. In addition we don't think that the metrics of the event loop is important because you can easily figure out that the thread is busy or not looking at the CPU metrics.

however for the blocking tasks, it's important to have metrics because there is an underlying thread pool and the sizing of this pool can be correlated with these metrics.

**Comment by marcust** [comment]
Well, it is not about busy or not but rather too busy, no? If the event loop has a very long queue I can get great throughput but shitty latency and if I want to see that I currently have no way to do that other than measuring response metrics and guessing the cause. 

If I get it correctly the overhead of metrics (three != null checks) is already there because `wrapTask` is used for all. And we could add that explicitly to the SPI, as `createEventLoopMetrics` and `createAcceptorEventLoopMetrics` that have a default method that is returning `null` and a warning about performance.

**Comment by vietj** [comment]
actually I would like to remove the wrapTask on event loop in the future because it's not strictly necessary in some cases.

I think we should rather try to have a callback that provides access to `SingleThreadEventExecutor` that exposes the number of pending tasks, if that's what you are looking for

**Comment by marcust** [comment]
`SingleThreadEventExecutor` sounds like a good starting point, but I actually don't understand where I would interface with that.

**Comment by vietj** [comment]
I think that we should extend the metrics interface to get a callback when an event loop is created and pass this as ref, so the metrics implemnetation can poll it when it needs

**Comment by marcust** [comment]
So from how I see it, the problem is that the actual `SingleThreadEventExecutor` is hidden in the NioEventLoopGroup and it's `newChild` method. So no easy access here, or do I read that wrong?

I think it would still be easier via the `PoolMetrics`.

**Comment by vietj** [comment]
I don't think so, you can schedule the callback as a task on the event loop and call the metrics in this task
