### ISSUE TITLE
localCosumer 100x slower than consumer in Clustered mode

### ISSUE THREAD

**Issue by oli-h** [eclipse-vertx/vert.x#2617]
Reproducer: https://gist.github.com/oli-h/e44c9e42033bd10945dc6c6afa460fcb

Tested with Vertx 3.5.3 and 3.5.0 on a Core i7-69xx:
- `consumer` handles 100'000 to 150'000 per second
- `localConsumer` is **factor 100 slower**: only ~1'500 per second can be delivered (and CPU-Load is high)

With Vertx 3.4.0 and 3.4.2 observations are different: Here, both types (consumer and localConsumer) are quite slow

Prior to 3.4.0 (e.g. 3.3.3) there seems to be no support for Infinispan-Cluster (or I didn't find the appropriate dependencies)

_Notes:_
- _I found #1764, but I think this was a different case as the performance panalty was only a few percent - not factor 100_
- _I also found https://github.com/eclipse/vert.x/commit/3ed3fea53990e31bdf63762c0bd67f1a0a5d6dc3 - this probably addresses the same basic issue, but from the sender's perspective_

**Comment by vietj** [comment]
can you open this issue in the infinispan cluster manager repository ? I see that your reproducer uses infinispan

thanks

**Comment by oli-h** [comment]
> can you open this issue in the infinispan cluster manager repository ? I see that your reproducer uses infinispan

I'm not sure if this problem is limited to Infinispan Cluster Manager - Ididn't test it with other cluster setups.

**Comment by vietj** [comment]
well it can't be tested in this project since it uses infinispan, you can provide at least a project that reproduces it (with a pom.xml)

**Comment by vietj** [comment]
or can you provide a test that uses the fake cluster manager from the vertx test suite ?

**Comment by brian65535** [comment]
Hi @vietj, we observe the similar thing in our project. localConsumer is much slower (up to 100x slower) in clustered mode unless localOnly is set to true in DeliveryOptions. Here is the link to a reproducer: https://github.com/brian65535/eventbustest

**Comment by vietj** [comment]
@brian65535 I used your reproducer and I believe the performance degradation lies in the reproducer itself.

The reproducer will create/unregister a new consumer for every message that is sent. It should instead always use the same consumer. So this test does not actually measure the throughput of sending messages but instead the throughput at which you can create/unregister consumers on the event bus.

You can expect this to be much lower in clustered mode because consumer registration in local mode is a simple local operation (more or less a concurrent hashmap update with a CAS) and in clustered mode it involves updating the clustered async map which involves IO operations.

If you modify the test to perform the registration once, then you will measure the cost of sending messages with both setups. Here is what I used for the send-send scenario of your test:

```
        private void sendSend(String replyAddress, AtomicBoolean isFinished, AtomicLong count, long duration, long startTime) {
            MessageConsumer<String> messageConsumer = testVariables.useLocalConsumer ? vertx.eventBus().localConsumer(replyAddress) : vertx.eventBus().consumer(replyAddress);
            messageConsumer.handler(sendSendHandler(messageConsumer, isFinished, count, duration, startTime));
            vertx.eventBus().send("SEND_SEND", MESSAGE, new DeliveryOptions(testVariables.deliveryOptions).addHeader("replyAddress", replyAddress));
        }

        private Handler<Message<String>> sendSendHandler(MessageConsumer<String> originalConsumer, AtomicBoolean isFinished, AtomicLong count, long duration, long startTime) {
            return message -> {
                originalConsumer.unregister();
                if (MESSAGE.equals(message.body())) count.incrementAndGet();
                else logger.warn("Incorrect reply message");

                if (System.nanoTime() - startTime >= duration * 1000000000L) {
                    if (!isFinished.getAndSet(true)) vertx.eventBus().send("COLLECT", count.get(), testVariables.deliveryOptions);
                } else {
                    sendSend(message.toString(), isFinished, count, duration, startTime);
                }
            };
        }
```

In this case I observe the following results for the send-send scenario with Hazelcast with my comments.

```
// This number if roughly half of the local mode which is expected since there is more work involved when sending a cluster message
TestVariables: numInstances=4, numTestEvents=16, clusterMethod=Hazelcast, useLocalConsumer=false, deliveryOptions=default, deliveryMethod=Send_Send
11595482

TestVariables: numInstances=4, numTestEvents=16, clusterMethod=Hazelcast, useLocalConsumer=false, deliveryOptions=localOnly, deliveryMethod=Send_Send
21882740

// This low number is expected because the cluster has to make a lookup that involves a cluster operation since we don't cache the absence of consumer. The absence of consumer is not put in the cache to avoid polluting the cache with potentially lot of information. It is a trade off.
TestVariables: numInstances=4, numTestEvents=16, clusterMethod=Hazelcast, useLocalConsumer=true, deliveryOptions=default, deliveryMethod=Send_Send
284845

TestVariables: numInstances=4, numTestEvents=16, clusterMethod=Hazelcast, useLocalConsumer=true, deliveryOptions=localOnly, deliveryMethod=Send_Send
22148337
```

**Comment by brian65535** [comment]
@vietj Thanks for the detailed explanation.

Your posted code snippet seems to be identical to the original code (probably mistakenly copied?). But I see your point, and this is how I modify it and rerun:
https://github.com/brian65535/eventbustest/compare/send_send?expand=1

Results:

Cluster | Consumer | Delivery Options | Delivery Method | #<br>(no reuse) | #<br>(reuse)
-------------- | ----------------- | --------------- | -------------- | -: | ----:
No | consumer | default | send-reply | 10,133,933 | 9,795,350
No | consumer | default | send-send | 11,515,381 | 18,257,848
No | consumer | localOnly | send-reply | 10,983,083 | 10,420,296
No | consumer | localOnly | send-send | 12,033,354 | 21,383,913
No | localConsumer | default | send-reply | 10,695,797 | 10,552,179
No | localConsumer | default | send-send | 11,129,014 | 22,774,070
No | localConsumer | localOnly | send-reply | 10,246,302 | 10,310,709
No | localConsumer | localOnly | send-send | 10,566,403 | 22,317,016
Hazelcast | consumer | default | send-reply | 4,369,049 | 4,287,025
Hazelcast | consumer | default | send-send | 162,708 | 13,116,594
Hazelcast | consumer | localOnly | send-reply | 4,487,854 | 5,469,122
Hazelcast | consumer | localOnly | send-send | 2,259,842 | 19,988,959
Hazelcast | localConsumer | default | send-reply | 499,722 | 470,877
Hazelcast | localConsumer | default | send-send | 279,049 | 282,477
Hazelcast | localConsumer | localOnly | send-reply | 4,339,591 | 4,657,155
Hazelcast | localConsumer | localOnly | send-send | 8,827,267 | 17,763,304

With consumer reused, send-send scenarios outperform send-reply scenarios by 2+ times, even under no cluster situations (except for "clustered mode" + "localConsumer" + "default DeliveryOptions", which is, as you said, bound by the cluster lookup operations due to consumer cache miss).

I guess it kinda makes sense because send-reply requires registering reply handlers, which is similar to registering message consumers, but probably in a more optimized way.

However there are some functionally inconveniences for reusing consumers, for example, you can't simply access final local variables in a sender's method, which otherwise can be easily done with a reply handler or a new consumer registered by the sender. And there is no guarantee which verticle will receive a message if a consumer is reused and registered by multiple verticles, whereas reply handlers or new registered consumers will be handled by the same verticle (and event loop thread) as of the original sender.

Anyways, thanks for your time. This is my takeaways:
- registering non-local consumers is expensive in the clustered mode
- reuse consumers if possible
- send-reply seems to perform better then send-send with consumers create/unregister for each message in the clustered mode
- use localConsumer and localOnly delivery for local messages to avoid consumer cache miss lookup penalty in the clustered mode
