### ISSUE TITLE
Vertx hangs instead of closing while using Micrometer

### ISSUE THREAD

**Issue by renannprado** [eclipse-vertx/vert.x#2943]
I'm trying to use Vertx + Micrometer and I see that that when I want to call `vertx#close` the application doesn't exit and some threads from the Micrometer class stay there forever.

However when I run the both standalone (either Vertx or Micrometer), everything is fine. So this issue only happens when I try to use both at the same time.

Here's a screen shot of what I see when I try to close the vertx instance, but it hangs.

Below you can find a link to the repository capable of reproducing the issue.

![hanging_threads](https://user-images.githubusercontent.com/2359543/57571730-df3b9200-7411-11e9-8ab1-82793670f1c1.png)

https://github.com/renannprado/vertx-micrometer-issue

**Comment by renannprado** [comment]
Nevermind, I was creating another `vertx` instance in the `MetricsModule` class **by mistake**.
I only realized after some time.

**Comment by nixos89** [comment]
Hi @renannprado ,
I've ran across this issue in  Gitter _vertx-users_ while I was searhing for similar problem that I'm having (although in Java, NOT Kotlin). Where are you, i.e. in which Verticle, are you supposed to set `MicrometerMetricsOptions` ...is it only necessary to do it **ONLY in Main (i.e. Application) Verticle or each one that is being deployed**? 
Thank you in advance. :)

**Comment by renannprado** [comment]
@nixos89 I would expect that setting it only once should be the way to go, but I wouldn't trust my words on this tbh 'cause I was just getting started with vert.x and at some point I gave up on it - I no longer use vert.x.

I was using dagger back then and this is what I had:


```kotlin
import dagger.Module
import dagger.Provides
import io.micrometer.statsd.StatsdMeterRegistry
import io.vertx.core.Vertx
import io.vertx.core.VertxOptions
import io.vertx.micrometer.MicrometerMetricsOptions
import javax.inject.Singleton

@Module
object VertxModule {

    @Provides
    @Singleton
    fun provideVertx(vertxOptions: VertxOptions): Vertx {
        return Vertx.vertx(vertxOptions)
    }

    @Provides
    @Singleton
    fun vertxOptions(metricsRegistry: StatsdMeterRegistry): VertxOptions {
        return VertxOptions()
                .setMetricsOptions(
                        MicrometerMetricsOptions()
                                .setEnabled(true)
                                .setJvmMetricsEnabled(true)
                                .setMicrometerRegistry(metricsRegistry)
                )
    }
}
```

**Comment by nixos89** [comment]
@renannprado thank you for quick response. :) I'm trying to get it to show more info in VisualVM by ALSO setting **[domain](https://vertx.io/docs/vertx-micrometer-metrics/java/#_configuration_examples_3)** under `com.ns.vertx.pg`, but it keeps showing ONLY **metrics** as domain in MBeans section which can be seen in following screenshot 

![Screenshot from 2020-07-22 16-47-22](https://user-images.githubusercontent.com/12121415/88191125-618d2c00-cc3b-11ea-88c1-ce9747c54f07.png)

...and that's why I've asked you in 1st place is it necessary to do it for ALL verticles or just Main/Application one. I've also seen in your code that you have set `MicrometerRegistry` and I have added it as well as explained [here](https://vertx.io/docs/vertx-micrometer-metrics/java/#_configuration_examples_3) in Vertx-Micrometer-Metrics Docs.
Is there something I'm missing?

**Comment by renannprado** [comment]
@nixos89 unfortunately I have no clue :disappointed: . I'd suggest to try to start this conversation again in Gitter, there you'll get in touch with the core devs, they can help you much more than I can.

**Comment by nixos89** [comment]
@renannprado I will, thanks for your time. ;) Cheers!
