### ISSUE TITLE
NPE when calling JsonArray#copy() in case of a `null` list

### ISSUE THREAD

**Issue by ctron** [eclipse-vertx/vert.x#2993]
Vertx: 3.7.x

Assuming the following code:

~~~java
JsonArray a = new JsonArray((List)null);
JsonArray b = a.copy(); // NPE
~~~

I am not sure of the correct fix is to allow that, or throw the NPE when calling the constructor. But throwing the NPE in the copy method seems wrong to me.

**Comment by vietj** [comment]
I think it should not accept null list indeed and fail fast thanks for reporting

**Comment by ctron** [comment]
I just fund out that vert.x itself injects `null`:

~~~java
final JsonArray array = new JsonArray(Buffer.buffer("null"));
array.copy();
~~~

That is e.g. used by the HTTP routing, when calling `io.vertx.ext.web.impl.RoutingContextImpl.getBodyAsJsonArray()`

**Comment by pmlopes** [comment]
Looking at this, I think we should add a factory method instead of a constructor, so if the input is null like the examples above, returns null as it is allowed by the json spec.

E.g:

```java
JsonObject = JsonObject.from(null) // returns null
```

And perhaps deprecate the constructors?

**Comment by vietj** [comment]
that's a good idea, tho codetrans should then be supported for translating such expressions in our doc when we use it

**Comment by vietj** [comment]
that being said we already have a factory method on JSON:

JSON.decodeValue which I think is better because it will decode to object and then the user must do a type check (we would have a similar issue with JsonObject.from("[]");

So we should for now set in the javadoc that this constructor must be used when the developer is sure that that string is not null and is an actual json array. If the user is unsure then he should use JSON.decodeValue(str)

In the constructor itself we should make sure that we always get a valid List for the underling object. Same for JsonObject with a map

**Comment by vietj** [comment]
we'll address this into 2 issues, one for vertx-web that should better decode JSON using decodeValue and one in this project to have JSON object and array throw an exception at instantiation time when the corresponding char representation is not valid

**Comment by vietj** [comment]
See https://github.com/vert-x3/vertx-web/issues/1317

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/issues/3001
