### ISSUE TITLE
SSL and chunkedWriter

### ISSUE THREAD

**Issue by himanshumps** [eclipse-vertx/vert.x#2997]
Why is the chunkedwriter made as default when SSL is enabled ?

https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/HttpServerImpl.java#L401

**Comment by vietj** [comment]
when SSL is disabled using `sendFile` (like in `NetSocket` or `HttpServerResponse`) will send a `FileRegion` object (that is just a reference to a file on the filesystem) and the `NioSocketChannel` will take care of sending the file efficiently.

when SSL is enabled, `FileRegion` cannot be used anymore because the file must be encoded and thus instead of `ChunkedFile` will be used which is also a reference to a file. Using `ChunkedFile` requires to add the `ChunkedWriteHandler` that will split the actual file into actual `ByteBuf` messages that will be sent.

**Comment by himanshumps** [comment]
Why it is done for all the operations when SSL is enabled?

For basic http REST services which doesn't involve file, this will enable the chunked writer. 

Can't we setup the FileRegion to use ChunkedFile in case of SSL.
