### ISSUE TITLE
allow naming the thread pool threads vertx uses

### ISSUE THREAD

**Issue by radai-rosenblatt** [eclipse-vertx/vert.x#3052]
this is useful when running multiple vertx instances in the same JVM

**Comment by tsegismont** [comment]
What's your use case for multiple Vert.x instances?

**Comment by radai-rosenblatt** [comment]
integration testing - i have unit tests that spin up clustered vertx. this results in multiple vertx instances in the same JVM and chaos in the logs :-)

**Comment by Jotschi** [comment]
I also think this might be useful. I'm currently adding multitenancy support for my application. In order to save memory the goal is to run multiple Vert.x servers within one JVM. Every tenant gets a dedicated server assigned which can be used. Logging is however still handled in a static way and thus the log messages can't be mapped to a tenant. Prefixing the thread would allow me to differentiate the logged line.

Another option for my problem would be to also inject the logger in every object where logging is needed. This way even logging would be tenant specific. I'm still checking the pros/cons.

**Comment by radai-rosenblatt** [comment]
@Jotschi - an advantage to being able to name the threads over injecting the logger is that it would also make for nicer thread/heap dumps.

**Comment by hutchig** [comment]
I see the VertxThreadFactory is [created](https://github.com/eclipse-vertx/vert.x/blob/b798f1f63f9e0e27d440508eb311813b59de7238/src/main/java/io/vertx/core/impl/VertxImpl.java#L138) with a thread name prefix matching the worker pool as part of creating
the ExecutorService. If #1539 does provide for a custom ExecutorService it would be worth remembering the requirement here on Thread naming (as well as how/if to support what BlockerThreadChecker does).

**Comment by vietj** [comment]
there is now a possibility to provide a custom thread factory
