### ISSUE TITLE
Vertx need await / async feature java side

### ISSUE THREAD

**Issue by champax** [eclipse-vertx/vert.x#3257]
### Version

3.8

### Context

Currently you have the choice between callback hell, ending with complex business code at tabulation 8192, or to rely on complex future headaches.

In both cases, you may/will end up, even with best efforts, with un-readable and/or un-maintainable complex business code.

RUST (https://rust-lang.github.io/async-book/01_getting_started/04_async_await_primer.html) and python 3 (https://docs.python.org/3/library/asyncio-task.html) have support for async / await syntax, which basically hides this boring level of useless complexity.

Some JS stuff try to mitigate also this problem (https://github.com/pmlopes/vertx3-nashorn.next/blob/master/examples/async-await/src/server.js).

I assume vertx, java server side, critically need this.

I didnt find any clues about this, so i open this bug. Feel free to do what you want with it, but i assume bypassing this may be a very bad idea for vertx.

### Do you have a reproducer?

Refer to some samples, like https://stackoverflow.com/questions/49799865/how-to-refactor-chain-of-asynchronous-calls-in-vertx-to-avoid-the-callback-hell

* Link to github project/gist

### Steps to reproduce

Use vertx.

### Extra

Vertx 3.8 and before.

**Comment by aesteve** [comment]
Unfortunately when looking at Java, it's not really "Vert.x's fault".
You're comparing language features (Rust, JavaScript) to the Java version of a polyglot-library.

Supporting async/await in Vert.x + Java would required Java (the language) to implement this. Vert.x could create an `async()` function, but that would end-up being the "mess" you describe (either `Future` or callbacks). Since, at the moment there's no way to tell the JDK we're "suspending" the execution.

So, that's totally dependent on the language.


2 things you may find interesting:
* Kotlin's koroutines: https://vertx.io/docs/vertx-lang-kotlin-coroutines/kotlin/ Kotlin has quite such a nation of async/await through `suspend`
* [Project Loom](https://openjdk.java.net/projects/loom/) that would introduce such a concept in Java, that for sure the Vert.x team is looking at closely.
You may be interesting in Kotlin's

**Comment by pmlopes** [comment]
The latest `es4x` runtime using the 4.0.0-milestone releases can already do `async` / `await` on both JS promises and vert.x `Future` types:

```js
async function futureTest3 () {
  return await vertx              // <---
    .createHttpServer()
    .requestHandler(req => {})
    .listen(12345);
}

futureTest3()
  .then(function (result) {
    should.assertNotNull(result);
    should.assertEquals('io.vertx.core.http.impl.HttpServerImpl', result.getClass().getName());
    should.assertEquals(12345, result.actualPort());
    test.complete();
  })
  .catch(function (err) {
    should.fail('Expected to create a HTTP Server on port 12345');
  });
```

**Comment by vietj** [comment]
can't add more to what @aesteve said - closing this as it's a question/concern/trade/opinion/debate that we are aware of
