### ISSUE TITLE
Bug: In existing FutureImpl: Wrong exception-handling

### ISSUE THREAD

**Issue by knotenpunkt** [eclipse-vertx/vert.x#3318]
vertx 4 milestone 4

```
private void doDispatch(Handler<AsyncResult<T>> handler) {
    if (context != null) {
      context.dispatch(this, handler);
    } else {
      handler.handle(this);
    }
  }

```
thats the existing doDispatch-Method in your Future-Implementation.
**The Problem is in the else-path.**

if the handler throws an exception, the caller-side in the if-path is not abborted, cause the exception is caught anywhere in the context.dispatch......

in the else-path the exception abborts the caller-side.

**So we have there a different behaviour in the cases** if in the promise/Future is a context registered or not.

**I guess we need here something like this:**

```
} else {
try
{
      handler.handle(this);
}
catch(Throwable t)
{
//report t to the current-Context
}
}
```
that should not abbort the caller-side

lg knotenpunkt

**Comment by knotenpunkt** [comment]
the bug still exists: https://github.com/eclipse-vertx/vert.x/blob/e29acb4e06ac79d04e4f54ddcc5936deb74c5326/src/main/java/io/vertx/core/impl/FutureImpl.java#L123

**Comment by vietj** [comment]
this is the expected behavior, without a context the exception cannot be reported properly (beside logging) and we let the exception bubble up on the caller stack so it can eventually be reported to the an above context. In Vert.x 4 such promise should not be created and instead promise should be created from a context. This is the same behavior than in Vert.x 3

**Comment by knotenpunkt** [comment]
@vietj hmmm ok i will take a new look on it, but i think the issue was at the time i created it a valid one
