### ISSUE TITLE
[Doc] Broken link on https://vertx.io/docs/vertx-junit5/java/

### ISSUE THREAD

**Issue by violette** [eclipse-vertx/vert.x#3544]
On https://vertx.io/docs/vertx-junit5/java/, there is a broken link at the bottom of the page: on the JUnit 5 additional extensions, the 
link to [Vert.x Junit 5 Web Client](https://vertx.io/docs/vertx-junit5-web-client/java/) leads to a 404

**Comment by tsegismont** [comment]
@slinkydeveloper can you please take a look?

**Comment by slinkydeveloper** [comment]
We should probably remove it because it's only vertx 4

**Comment by slinkydeveloper** [comment]
@violette if you use vertx 4, please give a look at the new home of this package https://github.com/reactiverse/reactiverse-junit5-extensions/

We cannot serve these docs because of a circular dependency issue that breaks the docs build (which is also the reason why we're not releasing this package anymore under vertx official packages in vertx 4)
