### ISSUE TITLE
End handler not invoked when Websocket is closed on server side (without receipt of close frame)

### ISSUE THREAD

**Issue by sfitts** [eclipse-vertx/vert.x#3577]
### Version

3.9.2

### Context

Websocket converted to a FlowableReadStream no longer signals completion if the socket is closed *without* the receipt of a close frame.  We noticed this because our metrics told us that we were "leaking" web socket connections after we switched to Vert.x 3.9.x.  The decrement of the value used for this gauge occurs when the `FlowableReadStream` created from a web-socket (using `FlowableHelper.toFlowable`) completes for any reason.  However, this is no longer occurring when the socket is closed due to an idle timeout in our Nginx layer.

### Do you have a reproducer?

https://gist.github.com/sfitts/395223e48491782e5837378772bc95bf

The referenced test passes on 3.8.5 and fails on 3.9.2.

### Extra

This behavior change is due to the fact that the "endHandler" is no longer invoked as part of explicit close processing.  That change was made in commit -- https://github.com/eclipse-vertx/vert.x/commit/763b9b55941c02df820528e311ff21c0181335d8.  Note that prior to this the endHandler was invoked during `handleClosed`, now it is only invoked on the receipt of an explicit close frame.

If the new behavior is expected/correct, then the `FlowableReadStream` will need to be modified so that it can terminate when a close occurs in this manner (I'm not sure if it can since I don't see any place to hook when that happens).

**Comment by sfitts** [comment]
One additional note -- in our code we are using the Web extension version of websockets, so we have an instance of `SockJSSocket` which is what we are converting to the `FlowableReadStream`.  That said, the actual work is done by the base websocket and it was a change in this code that changed the behavior here.  However, it could be that something in the of the layers above this needs to change (at which point this issue will need to be moved to the appropriate repository).

**Comment by vietj** [comment]
@sfitts the behavior is actually correct (it happens similarly for other streams like `HttpServerRequest` or `NetSocket`), I will have a look at `FlowableReadStream`

**Comment by vietj** [comment]
Currently the test pass with 3.9.3-SNAPSHOT because we have made this change : https://github.com/eclipse-vertx/vert.x/issues/3531 . The end handler should always be called on both sides when a normal termination of the `WebSocket` happens (i.e with an handshake) and should not be called when the TCP sockets is closed (instead the exception handler should be called).

**Comment by vietj** [comment]
So I think indeed we have a bug in 3.9.2 but it's due to the incorrect implementation of the WebSocket handshake. It shall be fixed in 3.9.3 which is to be released soonish. I've added tests to ensure this behavior (https://github.com/eclipse-vertx/vert.x/commit/ea8922249727cae18c530c53006d57f6e34e0464)

**Comment by sfitts** [comment]
FYI -- tested our use case (connection termination due to idle timeout) on 3.9.3-SNAPSHOT and confirmed that it is fixed.
