### ISSUE TITLE
Vert.x HTTP server on port 0 and MQTT client issue

### ISSUE THREAD

**Issue by cescoffier** [eclipse-vertx/vert.x#3584]
### Questions

This issue has been reproduced in Quarkus, but looks Vert.x specific. 

In this use case, the HTTP verticle (start the HTTP server) instances (depending on the machine, but 8 in my case) are configured to listen on the port 0 (so dynamic binding). At the same time as the HTTP verticle start, an MQTT client is created and connect to an MQTT server.  

The HTTP server cannot bind to the port, failing with a Bind exception.

### Version

The code works with Quarkus 1.7 (Vert.x 3.8.5) and fails with Quarkus 1.8.1 (Vert.x 3.9.2). 

### Do you have a reproducer?

Reproducer available on:
https://github.com/smallrye/smallrye-reactive-messaging/issues/778

### Steps to reproduce

1. Download an unzip
2. Start MQTT server - `docker run -p 8080:8080 -p 1883:1883 hivemq/hivemq4`
3. `mvn compile quarkus:dev`
4. Boom

You can override the Vert.x version by declaring a dependency in the `pom.xml` file.

### Extra

* if you start the MQTT client before or after it works
* if you debug, it works - probably a timing exception

**Comment by vietj** [comment]
do you know if that happens with only Vert.x and if the reproducer can be adapted ?

**Comment by cescoffier** [comment]
I don’t believe it can be easily adapted without writing a lot of code to
reproduce what’s happening.

**Comment by vietj** [comment]
I tried reproducing it using Mosquito public server and it worked correctly.

The reproducer does not have explanations on how to reproduce it.

I commented on the referenced issue.

**Comment by vietj** [comment]
note: the reproducer binds HTTP server on a random port

**Comment by cescoffier** [comment]
I provided the steps to reproduce in this issue description:

```
1. Download an unzip
2. Start MQTT server - docker run -p 8080:8080 -p 1883:1883 hivemq/hivemq4
3. mvn compile quarkus:dev
4. Boom
```

**Comment by cescoffier** [comment]
With the public mosquitto server it works (for me) in runner mode, but not with `mvn compile quarkus:dev`. Can you try with that mode?

With hive, it fails in both cases (for me).

**Comment by vietj** [comment]
I will have a try

**Comment by vietj** [comment]
Here is what happens:

1/ a `WebDeploymentVerticle` is deployed by `VertxHttpRecorder` with multiple instances using a `Supplier` returning the *same* verticle instance
2/ all instances start an HTTP server with an `HttpServerOptions` argument
3/ the first instance to call listen and enter the synchronized section will actually bind an HTTP server
4/ when the HTTP server is actually started, the callback will update the `HttpServerOptions` with the actual port that was bound

It happens that one deployment of the `WebDeploymentVerticle` will call listen *after* the actual HTTP server is bound and use the updated `HttpServerOptions` and try to bind the verticle using now the port. This will not be detected as a shared port by the `HttpServer` because of the modification done previously with new shared HTTP server ID, the initial server ID is something like `localhost/${deploymentId}` and the server with the explicit port is `localhost` (because we use the deployment id only when the port is 0).

The most appropriate way to solve this is that `WebDeploymentVerticle` either does not update the `HttpServerOptions` on a callback, or that the `Supplier` does not return a single of the same verticle (the javadoc says `It must not return the same instance twice.`)

**Comment by cescoffier** [comment]
Thanks a lot @vietj!
That sounds easily fixable! I will change the Quarkus supplier.

Any idea why it was not happening in Vert.x 3.8.5?

Le mar. 29 sept. 2020 à 14:26, Julien Viet <notifications@github.com> a
écrit :

**Comment by cescoffier** [comment]
I don't believe it return the same instance:

```java
vertx.deployVerticle(new Supplier<Verticle>() {
            @Override
            public Verticle get() {
                return new WebDeploymentVerticle(httpServerOptions, sslConfig, domainSocketOptions, launchMode,
                        httpConfiguration.insecureRequests);
            }
        }, new DeploymentOptions().setInstances(ioThreads), new Handler<AsyncResult<String>>() {
            @Override
            public void handle(AsyncResult<String> event) {
                if (event.failed()) {
                    futureResult.completeExceptionally(event.cause());
                } else {
                    futureResult.complete(event.result());
                }
            }
        });
```

**Comment by cescoffier** [comment]
@vietj Closing this issue. I opened a PR in Quarkus directly: https://github.com/quarkusio/quarkus/pull/12401

**Comment by vietj** [comment]
no specific idea, this is racy, so it could happen before but was not
visible.
