### ISSUE TITLE
Allow to specify use setInstances in deployVerticle for non default Constructor

### ISSUE THREAD

**Issue by pendula95** [eclipse-vertx/vert.x#3596]
#### Describe the feature

Currently it is only possible to pass DeploymentOptions().setInstances(int x) when deployVerticle(String var1, DeploymentOptions var2) is used. In other words if you have a verticle that has non default empty constructor you can not deploy multiple instaces using DeploymentOptions().setInstances(int x) as you will get error: **_Can't specify > 1 instances for already created verticle_**
To bypass this you can create a for loop like this:
```
for(int i = 0; i < x; i++) {
  vertx.deployVerticle(new SomeVerticle(object1, object2), new DeploymentOptions());
}
```
Also if you are using javarx2 you can do something like this:
```
vertx.rxDeployVerticle(new SomeVerticle(object1, object2),
                new DeploymentOptions())
                .repeat(x)
                .toList()
                .ignoreElement();
```

I would suggest to allow this via DeploymentOptions().setInstances(int x) as clearly end result is same and I don't see the point having this exception.

Expected to work after enhancement:
`vertx.deployVerticle(new SomeVerticle(object1, object2), new DeploymentOptions().setInstances(int x));`

@pmlopes mentioned on gitter that it is possible to achieve in vertx 4 with Supplier API.
`vertx.deployVerticle(() -> new SomeVerticle(object1, object2), deploymentOptions)`

**Comment by tsegismont** [comment]
There is a [`deployVerticle`](https://vertx.io/docs/apidocs/io/vertx/core/Vertx.html#deployVerticle-java.util.function.Supplier-io.vertx.core.DeploymentOptions-io.vertx.core.Handler-) method that takes a `Supplier`.

It's available already in Vert.x 3 and was added specifically to solve that problem.

I'm closing this issue, please reopen if there's a bug with this method.

I would advise not use loops or `repeat` operator in RxJava because the verticles will be considered as separated deployments and as such there is no guarantee the instances use available event loops evenly.
