### ISSUE TITLE
Blocked thread checker improvements

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3624]
In order to provide a listener to allow reporting via other means that logging.

**Comment by wowselim** [comment]
Hi @vietj! I'd like to work on this ticket if no one else picked it up yet. I would appreciate some extra details:
* Should this be configurable via `VertxOptionsConverter` or should it be similar to `VertxOptions#setClusterManager`?
* Would it be enough if we could pass in a `Consumer<BlockedThreadInfo>` and do our logging inside the consumer?

If yes, I would propose to add this consumer that takes the same parameters as the existing log message:
```java
"Thread " + entry.getKey() + " has been blocked for " + (dur / 1_000_000) + " ms, time limit is " + TimeUnit.MILLISECONDS.convert(timeLimit, maxExecTimeUnit) + " ms";
```

Something along the lines of:
```java
class BlockedThreadInfo {
  String threadName;
  long blockDurationActual;
  long blockDurationMax;
}
```

We could then use the existing `BlockedThreadChecker` and simply forward the three parameters to the consumer.

---

An alternative would be to allow passing in a whole new implementation of `BlockedThreadChecker`. In this case I would propose to extract an interface from the current implementation so that people could implement their own versions and pass that in, which would disable the default `BlockedThreadChecker`.

Please let me know if you had something else in mind!
