### ISSUE TITLE
NullPointerException when create websocket

### ISSUE THREAD

**Issue by gillbates** [eclipse-vertx/vert.x#3889]
### Questions

```
Promise<WebSocket> p = Promise.promise();
vertx.createHttpClient().webSocket(8080, "127.0.0.1", "", p);
p.future().onComplete(res -> {
    if (res.succeeded()) {
        System.out.println(res.result());
    } else {
        res.cause().printStackTrace();
    }
});
```
the code above will throw a NullPointerException

```
Exception in thread “main” java.lang.NullPointerException
	at io.vertx.core.http.impl.HttpClientImpl.webSocket(HttpClientImpl.java:299)
	at io.vertx.core.http.impl.HttpClientImpl.webSocket(HttpClientImpl.java:286)
	at io.vertx.core.http.impl.HttpClientImpl.webSocket(HttpClientImpl.java:351)
```

I wonder what will be the correct usage in this case?

### Version
4.03

**Comment by tsegismont** [comment]
This happens because the `Promise` is not bounded to any context.

https://github.com/eclipse-vertx/vert.x/blob/8d9bb2ba44ce51bf461e21217c501ea31aa019ae/src/main/java/io/vertx/core/http/impl/HttpClientImpl.java#L288-L299

In the code above, `promise.context()` returns `null` causing the NPE.

We need to take into account that the websocket client can be used outside a verticle.

**Comment by tsegismont** [comment]
@gillbates as a workaround, you can either run your code in a verticle or create a promise bound to a context:

```java
ContextInternal ctx = (ContextInternal) vertx.getOrCreateContext();
Promise<WebSocket> p = ctx.promise();
```

**Comment by vietj** [comment]
we can fix this , but you should rather do `vertx.createHttpClient().webSocket(8080, "127.0.0.1", "", p).onComplete(...)`

**Comment by gillbates** [comment]
thx for the replies above. We would adopt this workaround in our current version. And look forward the fix in incoming version :).
