### ISSUE TITLE
vertx 4.0.1 OAuth2AuthHandler.create(Vertx vertx, OAuth2Auth authProvider) && OAuth2AuthHandlerImpl.setupCallback

### ISSUE THREAD

**Issue by rzorzorzo** [eclipse-vertx/vert.x#3965]
### Version 

Which version(s) did you encounter this bug ?
4.0.1
### Context

the method invokes:
in setupCallback:
    if (callbackURL == null) {
      // warn that the setup is probably wrong
      LOG.warn("OAuth2AuthHandler was created without a origin/callback URL, setup is NO-OP");
      return this;
    }
this breaks previous implementations in vertx 3

"return this" should be removed.

**Comment by zepouet** [comment]
Hello, 

Same problem met with GitlabAuth for release 4.1.0.

Thanks a lot,
Best regards,

**Comment by pmlopes** [comment]
@zepouet @rzorzorzo this was a change to allow the openapi router builder to be able to create routers without having a callback installed.

I think we could address this in a different way, instead of silently log a warning and do a NO-OP, we can throw an exception, but while before we would throw an `IllegalStateException` we may need to define some well known exception type (XYZ extends ISE) to clearly identify the situation for OpenAPI yet, keeping the old contract (fail fast on bad config).

**Comment by zepouet** [comment]
Thanks Paulo,

I understand the reason. Maybe add a new signature to keep the old contract for OpenAPI ?

For my part, I met the problem when I am trying to run this project : https://how-to.vertx.io/web-and-oauth2-oidc/
You have the same issue with GitlabAuth than GithubAuth.
I think the example will be always wrong with exception.

Nicolas,

**Comment by pmlopes** [comment]
Fixed by: https://github.com/vert-x3/vertx-web/commit/97917b0ad77ee80bfd6d65ca2f87b57ff3ad2d6a

Also, the howto is updated to use 4.1.0 and also works with the fix. The new behavior is that the application would fail to start if the configuration is incorrect:

https://github.com/vertx-howtos/web-and-oauth2-oidc/commit/42890d4d10653a97c94cf29eb376001dc9aa3d09

If gitlab still doesn't work, please share with me some demo oauth2 config, so I can debug it further.

**Comment by rzorzorzo** [comment]
thanks for the response.

I think that since the callbackURL is no longer optional, the method: 
OAuth2AuthHandler.create(Vertx, OAuth2Auth)
should be removed, since it gives the impression that callbackURL can be null.

In addition, we now have to enter the callback url in the create method AND in the setupCallback method, which is redundant and misleading. Entering different urls will result in an error.
