### ISSUE TITLE
Event Loop Thread Pool Size with Hyperthreading on Linux

### ISSUE THREAD

**Issue by ErikSimonsen** [eclipse-vertx/vert.x#4019]
### Version

Quarkus Vert.x - Final 1.12.1

### Context

While testing out Vert.x i noticed that the size of the default Event Loop Thread Pool was 32-Threads on my linux-system.

However i have only 16 logical CPU's (8 physical-cores x 2 threads). 
Shouldn't the default number of Event Loop Thread Pool be twice the number of physical CPU-Cores instead of logical CPU's (so 16 instead of 32)? 

I checked https://github.com/eclipse-vertx/vert.x/blob/601baccefd6f108b561627ec240ed46ee81d2f93/src/main/java/io/vertx/core/impl/cpu/CpuCoreSensor.java#L53
and the value of 'Cpus_allowed' inside '/proc/self/status' seems to be the number of logical cpu's (so 16 for me), so hyperthreading was already calculated there. Therefore in my opinion it is not correct to double that size again.

### Extra

Processor: AMD Ryzen 7 2700x eight-core processor x 16
OS: Fedora 34 (Workstation Edition)
Java Version: 11

**Comment by vietj** [comment]
thanks that makes sense

**Comment by pmlopes** [comment]
The event loop thread pool is set to twice the number of logical cores. For example, on my Linux laptop I have:

https://ark.intel.com/content/www/us/en/ark/products/124968/intel-core-i7-8650u-processor-8m-cache-up-to-4-20-ghz.html

The `CpuSensor` reports:

```
fromJava: 8
fromProcFile: 8
```

Which is aligned with the info I can also read on `/proc/cpuinfo` The OS "sees" 8 logical cores, so the values are correctly loaded. If I read your specs correctly, your AMD will report 16 logical CPUs

https://www.amd.com/en/products/cpu/amd-ryzen-7-2700x

Just like my Intel because the number of threads is what gets reported in `/proc/cpuinfo`, so in the end your event loop thread pool will be by default 32.

**Comment by vietj** [comment]
thanks @pmlopes
