### ISSUE TITLE
Connection closed exception expected instead of timeout

### ISSUE THREAD

**Issue by neterium** [eclipse-vertx/vert.x#4170]
### Version

Which version(s) did you encounter this bug ?
4.0.3

### Context

When a vertx server is closed gracefully in a clustered vertx (all consumers unregistered, verticles undeployed, vertx closed), there are consumers in other servers that receive a timeout ReplyException. We would have expected that those consumers did not have to wait for the timeout to expire, and immediately receive an other error such as VertxException : Connection was closed.
I assume that when a verticle (or a consumer) is unregistered, vertx knows what are the pending requests, would it be possible to make them fail with an adequate exception instead of letting them expire in the sender ?

**Comment by vietj** [comment]
It seems complicated to do because we don't keep track of all received requests on the server.

It seems complicated to rely on the connection closed because when the connection is closed the bus can establish a new connection to send back the response.

We can investigate that a shutting down server will send a specific message to other peers before closing the TCP connection that will tell them to close the pending requests.

**Comment by neterium** [comment]
That would be a very nice feature indeed!

**Comment by vietj** [comment]
For now I will close this issue as this will likely not be implemented for years (it requires a modification of the event-bus protocol) : see https://github.com/eclipse-vertx/vert.x/issues/4170
