### ISSUE TITLE
Chrome don't use http/2.0 to get resources from vertx-server

### ISSUE THREAD

**Issue by TorRanfelt** [eclipse-vertx/vert.x#4189]
### Questions

Inspecting with developer tools Chrome uses http/1.1 when getting resources from my vert.x server even though https://vertx.io/docs/apidocs/io/vertx/core/http/HttpServerOptions.html states http/2.0 should be prioritized.

I haven't been able to find any information about Chrome doing something weird and when checking other sites h2 (i.e. http/2.0) is used.

I also haven't been able to find any information in the vert.x documentation about configuring the server-side for http/2.0. Only the client-side.

Am I missing something or is it a bug?

### Version

Vertx 4.2.1

**Comment by coding4m** [comment]
for h2:
new HttpServerOptions().setSsl(true).setUseAlpn(true).setKeyCertOptions(xxx).setTrustOptions(xxx);

h2c default is enable when not use ssl.

**Comment by TorRanfelt** [comment]
Thank you.

Any reason why it must be explicitly enabled when using ssl?

**Comment by pmlopes** [comment]
Most browsers do not support / implemented `h2c` (or is disabled by default).

So, most browsers will only handle `h2` in SSL + ALPN mode. There are a few reasons:

* Doing HTTP/2 negotiation in TLS with ALPN is much easier and doesn't lose round-trips like Upgrade: in plain HTTP does. And it doesn't suffer from the upgrade problem on POST that you get with plain-text HTTP/2.
* Most of the web doesn't support unsolicited `Upgrade: h2c` headers in requests and instead respond with 400 errors.
* Doing something else than HTTP/1.1 over TCP port 80 breaks in many of the cases since the world is full of old software and proxies.

**Comment by TorRanfelt** [comment]
@pmlopes Thanks for the explanation.
