### ISSUE TITLE
https://vertx.io/

### ISSUE THREAD

**Issue by bardiademon** [eclipse-vertx/vert.x#4426]
A question has occupied my mind

Why is the vert.x website written with the nest.js framework?

Why not use Java?

**Comment by vietj** [comment]
closing this as it's a non vertx core related issue

**Comment by vietj** [comment]
the web-site is fully handled by @michel-kraemer so I will let him speak here

**Comment by bardiademon** [comment]
I'm sorry, it was a question I did not know where to ask

**Comment by michel-kraemer** [comment]
@bardiademon Before I started designing the new website for Vert.x 4, I did a comprehensive comparison of various static website generators. The frameworks I evaluated were Vuepress, Hexo, Metalsmith (the one we used for the Vert.x 3 website), Hugo, Gatsby, Gridsome, plain Webpack, and JBake. Among those, only Hugo and JBake are not JavaScript frameworks (Hugo is written in Go, and JBake uses Java). The evaluation criteria were community support, rich ecosystem, good documentation, development speed, extensibility, use of modern technology, and compatibility. Unsurprisingly, JavaScript is the language of the web, so non-JavaScript frameworks could be ruled out quite quickly. Among the remaining ones, Next.js was the winner because it fulfilled all the criteria above.

I have to say I'm very happy with the decision. I've been using Next.js in various other projects since this evaluation and it always worked perfectly so far. The technology is modern and fast, there is active development, community support is awesome, and it's quite easy to extend the framework and create your own React components (which I make extensive use of for the Vert.x website).

I hope this answer helps. Let me know if you have further questions. It's probably best if you use the web-site channel on [Discord](https://discord.gg/6ry7aqPWXy) for this.
