### ISSUE TITLE
http responses from server are cut-off for certain files when Brotli compression is enabled.

### ISSUE THREAD

**Issue by codingchili** [eclipse-vertx/vert.x#4501]
### Version

vert.x 4.3.3.

### Context

Using a vertx http2 server with tls and configured with the new brotli support, some resources are cut-off in the response. This seems to be slightly rare, as it only seems to happen for 2/40 files loaded from an index page (one js file UTF-8 and one webfont, see reproducer).

Configured as documented here (note: brotli4j's requirement for native libs is missing from vert.x documentation)
https://vertx.io/docs/vertx-core/java/#_http_compression_algorithms

### Do you have a reproducer?

See: https://github.com/codingchili/vertx-brotli-reproducer

### Steps to reproduce

1. Create a vert.x http/2 server with tls and brotli enabled per the docs.
2. Request files from the server and note that files are cut-off. 

For instructions on running the reproducer, see README.md.

### Extra

Environment
* JVM: 17.0.1 (Oracle Corporation 17.0.1+12-39)
* OS:   Windows 10 10.0 amd64

Brotli version
```
implementation 'com.aayushatharva.brotli4j:brotli4j:1.8.0'
implementation 'com.aayushatharva.brotli4j:native-windows-x86_64:1.8.0'
```

Vert.x
```
implementation 'io.vertx:vertx-core:4.3.3'
implementation 'io.vertx:vertx-web:4.3.3'
```

**Comment by conet** [comment]
I'm tracking some something similar but in a different context, data being corrupted somehow in a long running chunked response (streaming). As far as I can tell this is caused by the default TLS protocol settings used by vertx. My workaround is setting these HttpServerOptions and HttpClientOptions:
```
...
  .setSslEngineOptions(new OpenSSLEngineOptions())
  .setEnabledSecureTransportProtocols(Set("TLSv1.3", "TLSv1.2").asJava)
```

Can you test if these work for you?

**Comment by conet** [comment]
Never mind, I tested myself and it does not solve your problem, will continue to investigate.

**Comment by vietj** [comment]
thanks for the reproducer

**Comment by conet** [comment]
You probably need to add the dependency based on your platform [here](https://github.com/codingchili/vertx-brotli-reproducer/blob/main/build.gradle#L21).

**Comment by vietj** [comment]
can you provide a maven build for the project ?

I'm not able to run it from IDE because of Gradle and Intellij and I really
would like to in order to easily debug it.

**Comment by conet** [comment]
@vietj I spent the whole day pursuing the issue I though is related to this and came up with this reproducer: https://github.com/conet/vertx-tls-reproducer

The project contains the description of what I'm seeing but because it happens when chunked encoding is used it's probably different, let me know if you think I should open a new issue for that problem (sorry that it's a bit more complex than simply running it in the IDE).

**Comment by codingchili** [comment]
@vietj which platform are you on? I've only added two natives to build.gradle for win x86 and linux x86. 

full list is available here including mac and arm, 
https://mvnrepository.com/artifact/com.aayushatharva.brotli4j

the snippet from the brotli4j docs for automatically choosing platform libraries during compile seems sketchy.

---
Added pom.xml and maven wrapper, for maven builds it should be able to automatically find the correct platform native.
I also committed .idea if it helps with running from IDEA, I've been debugging fine using IDEA + Gradle at least.

**Comment by conet** [comment]
After giving it a lot of thought I decided to open [another issue](https://github.com/eclipse-vertx/vert.x/issues/4509), sorry for hijacking this one but initially I really believed they might be related.

**Comment by ShreckYe** [comment]
I encountered the same issue with Brotli enabled and a `StaticHandler` serving my web app files. The HTML files are small so they are served with no problem but the JS bundle is cut-off at 8192 bytes. FYI, my OS is Ubuntu 22.04.1 LTS on x86-64.

**Comment by vietj** [comment]
I found the same issue using Brave and I investigated the code with files above 8192.

`io.netty.handler.codec.compression.BrotliEncoder` process 8192 size blocks and when a body is larger than 8192, then it will be split in several encoded blocks. I am not familiar with brotli but it seems to me that instead of encoding each chunk separately, each buffer should be handled the same way that `com.aayushatharva.brotli4j.encoder.BrotliOutputStream` works.

So I am enclined to believe that it is a brotli4j integration bug with Netty. I will try providing a different version of the `BrotliEncoder` that uses a similar implementation to `BrotliOutputStream` to see if that fixes the issue.

**Comment by codingchili** [comment]
@vietj I cannot reproduce the issue using vert.x 4.4.x with my tests.

it appears this was fixed in: vert.x 4.1.x (with the netty 4.1.89.Final upgrade) see:

- https://netty.io/news/2023/02/13/4-1-89-Final.html
- https://github.com/netty/netty/issues/12909
- https://github.com/netty/netty/pull/12924

Do you want to try to reproduce it before closing this issue?
