### ISSUE TITLE
End of trace is missing response status when using the client and upgrading the connection

### ISSUE THREAD

**Issue by Sgitario** [eclipse-vertx/vert.x#4631]
### Version

4.3.7

### Context

When sending the response trace [here](https://github.com/eclipse-vertx/vert.x/blob/011d271bf470600989a59a605dee05ae92034170/src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java#L170), the HttpClosedException is being provided instead of the response because [this condition](https://github.com/eclipse-vertx/vert.x/blob/011d271bf470600989a59a605dee05ae92034170/src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java#L164) is wrong in the first request when upgrading connections to HTTP/2:

The flag `streamEnded` is `false` making the condition pass and hence propagating the exception. This is only happening in the first request, the next request (when the connection has been upgraded) has the `streamEnded` flag to `true`. 

This flag is set to `false` in [Http1xUpgradeToH2CHandler](https://github.com/eclipse-vertx/vert.x/blob/011d271bf470600989a59a605dee05ae92034170/src/main/java/io/vertx/core/http/impl/Http1xUpgradeToH2CHandler.java#L110).

**Comment by Sgitario** [comment]
Apply the changes in this commit into the existing test in Http2TracerTest#testTracingWorksAfterUpgrading: https://github.com/eclipse-vertx/vert.x/compare/master...Sgitario:vert.x:reproduce_4631?expand=1

**Comment by vietj** [comment]
can't find it @Sgitario

**Comment by Sgitario** [comment]
> can't find it @Sgitario

What can't you find?

The commit https://github.com/eclipse-vertx/vert.x/commit/a9de075b01dfc71649af6e9218c58f116d961edf or the error?

**Comment by vietj** [comment]
the link for comparison does not produce anything

**Comment by Sgitario** [comment]
that's weird. Can you see the changes using the link to the commit? Anyway, the test that reproduces the issue is:

```java
@Test
  public void testTracingWorksAfterUpgrading() throws Exception {
    client.close();
    FakeTracer fakeTracer = new FakeTracer();
    setTracer(fakeTracer);

    client = vertx.createHttpClient(new HttpClientOptions()
      // setting policy always, if not the span with kind client is not sent
      .setTracingPolicy(TracingPolicy.ALWAYS)
      .setProtocolVersion(HttpVersion.HTTP_2));
    // Server always return "Ok"
    server = vertx.createHttpServer();
    server.requestHandler(req -> {
      req.response().end("Ok");
    });
    startServer(testAddress);
    waitFor(2);
    // request <1>
    client.request(requestOptions).onSuccess(request -> {
      request.send().onSuccess(response -> {
        complete();
      });
    });
    // request <2>
    client.request(requestOptions).onSuccess(request -> {
      request.send().onSuccess(response -> {
        complete();
      });
    });
    await();
    // There should be 4 spans: 2 of kind server and 2 of kind client.
    // This test is failing because the first request <1> is missing one span that is produced only when the connection is closed.
    // The next request <2> is working correctly: the two spans are properly generated.
    assertEquals(4, fakeTracer.getFinishedSpans().size());
    assertTrue("Span with kind server was not found!",
      fakeTracer.getFinishedSpans().stream().anyMatch(s -> SPAN_KIND_SERVER.equals(s.getTags().get(SPAN_KIND_KEY))));
    assertTrue("Span with kind client was not found!",
      fakeTracer.getFinishedSpans().stream().anyMatch(s -> SPAN_KIND_CLIENT.equals(s.getTags().get(SPAN_KIND_KEY))));
  }
```

In Http2TracerTest.

**Comment by vietj** [comment]
thanks for reporting this issue, it raises a few concerns with respect to HTTP/2 upgrade:

The HTTP/2 RFC specs mandates the following items

1. `Requests that contain a payload body MUST be sent in their entirety before the client can send HTTP/2 frames.` 
2. `The HTTP/1.1 request that is sent prior to upgrade is assigned a stream identifier of 1 with default priority values.  Stream 1 is implicitly "half-closed" from the client toward the server, since the request is completed as an HTTP/1.1 request.`

From the Netty perspective, the stream is seen as _half closed remote_, since the stream cannot receive anymore frames from the HTTP/2 upgraded channel.

From the Vert.x perspective, the stream is seen as _open_ since the header frame is processed but the stream is not ended e.g the stream can contain a body and we expect content messages.

The test ends the response in the request handler, when `req.response().end()` is called the stream transitions to `closed` state, but it could still process buffers.

So we do have this conflict happening and find a way to solve it.

One way could be to delay the actual close when the response is ended, which would I believe work but introduces some complexity (i.e a special case to handle). That is most likely what we will have to do to solve this.
