### ISSUE TITLE
More load balancing policies

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vert.x#5154]
In addition to the existing (round-robin and least request) policies in `io.vertx.core.loadbalancing.LoadBalancer`, we should have:

- [x] random
- [x] power of two choices

Possible contributor @machine424

**Comment by tsegismont** [comment]
@vietj can you elaborate about the hashing load balancing policies you talked to me about off-list? I understand this could be used to solve different cases, including sticky web sessions

**Comment by vietj** [comment]
this is used indeed for sticky session

this policy requires API modification because we need to pass this ID from the request (HTTP but not necessarily) to the load balancing algorithm.

most likely `EndpointResolver#Future<EndpointLookup> lookupEndpoint(ContextInternal,A)` needs to have this ID.

Users would use it using `RequestOptions` for HTTP requests and optionally set it.
