### ISSUE TITLE
vertx.getOrCreateContext() returns different instances

### ISSUE THREAD

**Issue by afloarea** [eclipse-vertx/vert.x#5155]
### Version

Which version(s) did you encounter this bug ?
4.5.5, 4.5.4

### Context

I encountered a strange behavior while writing a test using vert.x and sqlite. Basically `vertx.getOrCreateContext()` would return different instances (which have different context local data).

### Do you have a reproducer?

[This repo](https://github.com/afloarea/vertx-context-test) has a test (src/test/java/ContextTest) that can be run but sometimes it passes, sometimes it fails.

### Steps to reproduce

I was able to reproduce it by running the test in the repo but not always. I noticed that it tends to fail more if run from intellij. Using maven it only failed once.

Sample output of the test when it fails:

```
before json 6e2829c7
after json 51bd8b5c

org.opentest4j.AssertionFailedError: 
Expected :test
Actual   :null
```

### Extra

* Every time I ran the test using 'Debug' it always passed.
* I tried different JVMs (21 zulu and 17 temurin) and it didn't seem to affect anything
* I tried with both Vert.x 4.5.5 and 4.5.4 and it didn't seem to affect anything
* I tried running the test until failure (intellij config) and I noticed that it either fails in the first try or does not fail at all.
* I tried running the test using `@RepeatedTest(10)` and I noticed it failed at most once and the other 9 were successful.
* I only tried on Linux.

**Comment by tsegismont** [comment]
This happens because your test methods are invoked from a non Vert.x thread. In this case, the context returned by  `vertx.getOrCreateContext` is not guaranteed to be the same (internally, it's stored in a weak ref, so it's only the same until the JVM it needs to reclaim it).

You could either:

- make sure your test method run on the same context (https://vertx.io/docs/vertx-junit5/java/#_running_tests_on_a_vert_x_context), or
- store the context returned by `vertx.getOrCreateContext` in the method annotated with  `beforeEach` in a field for reuse.

@vietj I think we should only clarify the expectations in the Javadoc

**Comment by vietj** [comment]
good idea @tsegismont

**Comment by afloarea** [comment]
@vietj @tsegismont I understand, thank you for taking a look and for the clarification & suggestion
